### ISSUE TITLE
Audio Framework Bugs

### ISSUE THREAD

**Issue by jundl77** [intellimate/IzouSDK#19]

**Comment by jundl77** [comment]
the update method of a playlist does not work:

playlist.update(soundInfo.getTrackInfo(), trackInfo);

does nothing, while soundInfo.getTrackInfo() is the old track info, and trackInfo is the new trackInfo. After the call, the old track info in the playlist has not changed

**Comment by jundl77** [comment]
And the update method for a track info still does not work for me

**Comment by jundl77** [comment]
If the value changed, isNew(...) returns true which causes the optional to be empty while the changed value should be updated.. I think this is the issue

**Comment by LeanderK** [comment]
what do you mean with "new"?

**Comment by jundl77** [comment]
Ok, so I saw when an existing value has changed so that it would be overwritten, you cancel the update operation, so do you have to create a new TrackInfo everytime a value changes?

**Comment by LeanderK** [comment]
hmmm....thats the update code. i don't know where a bug could be

``` java
List<TrackInfo> list = new ArrayList<>(queue);
list.set(list.indexOf(old), newTrackInfo);
return new Playlist(queue, name, playbackModes, position);
```

**Comment by LeanderK** [comment]
isNew returns true only if values would be overwritten!

**Comment by jundl77** [comment]
Yes, its ok, I just made a new one and avoided the update method :P

**Comment by LeanderK** [comment]
if its a new TrackInfo, you create a new TrackInfo, if its an update to an existing tracking, you call the update method

**Comment by LeanderK** [comment]
this method is there to prevent misusing

**Comment by jundl77** [comment]
yeah ok, but the update method of the playlist still does not work

**Comment by LeanderK** [comment]
hmm ok, thats the code of the update method....i don't know where an error could be:

``` java
 /**
     * updates the TrackInfo-Object
     * @param old the old TrackInfo
     * @param newTrackInfo the new TrackInfo
     * @return the resulting new Playlist
     */
    public Playlist update(TrackInfo old, TrackInfo newTrackInfo) {
        List<TrackInfo> list = new ArrayList<>(queue);
        list.set(list.indexOf(old), newTrackInfo);
        return new Playlist(queue, name, playbackModes, position);
    }
```

**Comment by jundl77** [comment]
Hmm let me look, maybe its me

**Comment by LeanderK** [comment]
@jundl77 any more problems?

**Comment by jundl77** [comment]
Ok so that seems to work, but I have an exception here now when trying to start the addOn in izou (debug addOn works by the way now) So there is an abstract method error, whatever that is that cannot make a callback (I think?) I am not sure, here is the log, you will understand better than me. 

``` java
Connected to the target VM, address: '127.0.0.1:50774', transport: 'socket'
2015-06-19 00:45:11,128 DEBUG [main] org.intellimate.izou.main.Main (Main.java:92) - Starting Izou
2015-06-19 00:45:11,130 DEBUG [main] org.intellimate.izou.main.Main (Main.java:93) - Initializing...
2015-06-19 00:45:11,377 DEBUG [main] org.intellimate.izou.main.Main (Main.java:115) - Done initializing.
2015-06-19 00:45:11,378 DEBUG [main] org.intellimate.izou.main.Main (Main.java:116) - Adding addons..
2015-06-19 00:45:12,261 DEBUG [main] org.intellimate.izou.main.Main (Main.java:130) - retrieving addons & registering them
2015-06-19 00:45:14,148 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:97) - searching for addons in: /Users/julianbrendl/Google Drive/Programming/Java/Izou/target/lib
2015-06-19 00:45:14,166 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:100) - loading plugins
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%2520Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced'
[WeavingURLClassLoaderHelper] debug weaving 'javax.sound.sampled.AudioSystem'
[WeavingURLClassLoaderHelper] weaveinfo Join point 'method-execution(javax.sound.sampled.Line javax.sound.sampled.AudioSystem.getLine(javax.sound.sampled.Line$Info))' in Type 'javax.sound.sampled.AudioSystem' (AudioSystem.java:410) advised by around advice from 'org.intellimate.izou.system.sound.replaced.MixerAspect' (MixerAspect.java)
[WeavingURLClassLoaderHelper] debug generating class 'javax.sound.sampled.AudioSystem$AjcClosure1'
[WeavingURLClassLoaderHelper] debug weaving 'org.intellimate.izou.system.sound.replaced.MixerAspect'
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%2520Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced'
[WeavingURLClassLoaderHelper] debug weaving 'javax.sound.sampled.AudioSystem'
[WeavingURLClassLoaderHelper] weaveinfo Join point 'method-execution(javax.sound.sampled.Line javax.sound.sampled.AudioSystem.getLine(javax.sound.sampled.Line$Info))' in Type 'javax.sound.sampled.AudioSystem' (AudioSystem.java:410) advised by around advice from 'org.intellimate.izou.system.sound.replaced.MixerAspect' (MixerAspect.java)
[WeavingURLClassLoaderHelper] debug generating class 'javax.sound.sampled.AudioSystem$AjcClosure1'
[WeavingURLClassLoaderHelper] debug weaving 'org.intellimate.izou.system.sound.replaced.MixerAspect'
2015-06-19 00:45:14,887 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:102) - loaded: [PluginWrapper [descriptor=PluginDescriptor [pluginId=org.intellimate.izou.sdk, pluginClass=org.intellimate.izou.sdk.ZipFileManagerImpl, version=0.7.0, provider=intellimate, dependencies=[PluginDependency [pluginId=org.intellimate.izou, pluginVersion=null]]], pluginPath=/sdk-0.7.0], PluginWrapper [descriptor=PluginDescriptor [pluginId=jundl77.izou.izousound, pluginClass=jundl77.izou.izousound.ZipFileManager, version=1.5.0, provider=Julian Brendl, dependencies=[PluginDependency [pluginId=org.intellimate.izou.sdk, pluginVersion=null]]], pluginPath=/izousound-1.5]]
2015-06-19 00:45:14,887 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:106) - starting plugins
2015-06-19 00:45:14,892 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:112) - retrieving addons from the plugins
2015-06-19 00:45:14,904 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:114) - retrieved: [jundl77.izou.izousound.SoundAddOn@2b46a8c1]
2015-06-19 00:45:16,098 DEBUG [Thread-1] org.intellimate.izou.events.EventDistributor (EventDistributor.java:342) - EventFired: Event{type='response', source=Identification{identifiable=jundl77.izou.izousound.outputplugin.AudioFilePlayer@52580699}, descriptors=[izou.music.events.playerupdate], listResourceContainer=ListResourceProviderImpl{resources=[]}} from jundl77.izou.izousound.outputplugin.AudioFilePlayer
2015-06-19 00:45:16,101 FATAL [Thread-5] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.events.EventDistributor$$Lambda$54/1449625610@fe804bc
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at org.intellimate.izou.sdk.frameworks.music.events.PlayerUpdate.lifecycleCallback(PlayerUpdate.java) ~[?:?]
    at org.intellimate.izou.events.EventDistributor.lambda$processEvent$52(EventDistributor.java:343) ~[classes/:?]
    at org.intellimate.izou.events.EventDistributor$$Lambda$54/1449625610.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
2015-06-19 00:45:16,100 FATAL [Thread-4] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.addon.AddOnManager$$Lambda$51/1970779713@45f84cf0
java.util.concurrent.CompletionException: java.lang.NullPointerException
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.NullPointerException
    at org.intellimate.izou.sdk.frameworks.music.player.template.CommandHandler.setNextPreviousController(CommandHandler.java:85) ~[?:?]
    at jundl77.izou.izousound.outputplugin.AudioFilePlayer.<init>(AudioFilePlayer.java:39) ~[?:?]
    at jundl77.izou.izousound.SoundAddOn.prepare(SoundAddOn.java:26) ~[?:?]
    at org.intellimate.izou.sdk.addon.AddOn.register(AddOn.java:41) ~[?:?]
    at org.intellimate.izou.addon.AddOnManager$$Lambda$51/1970779713.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
2015-06-19 00:45:16,115 FATAL [Thread-4] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.events.EventDistributor$$Lambda$61/838340783@28f9401d
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at org.intellimate.izou.sdk.frameworks.music.events.PlayerUpdate.lifecycleCallback(PlayerUpdate.java) ~[?:?]
    at org.intellimate.izou.events.EventDistributor.lambda$processEvent$53(EventDistributor.java:345) ~[classes/:?]
    at org.intellimate.izou.events.EventDistributor$$Lambda$61/838340783.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
2015-06-19 00:45:16,116 FATAL [Thread-5] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.events.EventDistributor$$Lambda$62/1261943710@53b180eb
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at org.intellimate.izou.sdk.frameworks.music.events.PlayerUpdate.lifecycleCallback(PlayerUpdate.java) ~[?:?]
    at org.intellimate.izou.events.EventDistributor.lambda$processEvent$54(EventDistributor.java:346) ~[classes/:?]
    at org.intellimate.izou.events.EventDistributor$$Lambda$62/1261943710.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
2015-06-19 00:45:16,118 FATAL [Thread-6] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.events.EventDistributor$$Lambda$64/658950031@39d8c91
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at org.intellimate.izou.sdk.frameworks.music.events.PlayerUpdate.lifecycleCallback(PlayerUpdate.java) ~[?:?]
    at org.intellimate.izou.events.EventDistributor.lambda$processEvent$55(EventDistributor.java:349) ~[classes/:?]
    at org.intellimate.izou.events.EventDistributor$$Lambda$64/658950031.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
2015-06-19 00:45:16,141 FATAL [Thread-6] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.events.EventDistributor$$Lambda$72/2069427712@d5a6292
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at org.intellimate.izou.sdk.frameworks.music.events.PlayerUpdate.lifecycleCallback(PlayerUpdate.java) ~[?:?]
    at org.intellimate.izou.events.EventDistributor.lambda$processEvent$58(EventDistributor.java:365) ~[classes/:?]
    at org.intellimate.izou.events.EventDistributor$$Lambda$72/2069427712.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
2015-06-19 00:45:16,150 FATAL [Thread-6] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.events.EventDistributor$$Lambda$82/1957388737@965e7e1
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.AbstractMethodError: Method org/intellimate/izou/sdk/frameworks/music/events/PlayerUpdate.lifecycleCallback(Lorg/intellimate/izou/events/EventLifeCycle;)V is abstract
    at org.intellimate.izou.sdk.frameworks.music.events.PlayerUpdate.lifecycleCallback(PlayerUpdate.java) ~[?:?]
    at org.intellimate.izou.events.EventDistributor.lambda$processEvent$59(EventDistributor.java:367) ~[classes/:?]
    at org.intellimate.izou.events.EventDistributor$$Lambda$82/1957388737.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
```

**Comment by jundl77** [comment]
Ok so I found the issue, this code is not working:

``` java
        CommandHandler commandHandler = getCommandHandler();
        commandHandler.setNextPreviousController(command -> {
            if (command.equals(CommandResource.NEXT)) {
                nextSound();
            } else if (command.equals(CommandResource.PREVIOUS)) {
                previousSound();
            }
        });
        commandHandler.setPlayPauseController(command -> {
            if (command.equals(CommandResource.PLAY)) {
                resume();
            } else if (command.equals(CommandResource.PAUSE)) {
                pause();
            }
        });
        commandHandler.setTrackSelectorController(this::jumpToTrackInfo);
        commandHandler.setVolumeChangeableController(volume -> {
            setVolume(volume.getVolume());
        });
        commandHandler.setJumpProgressController(progress -> {

        });
```

The commandHandler is created, but the set methods throw the exception, did I do something wrong?

In fact 

``` java
    capabilities.setNextPrevious(true);
```

in here:

``` java
    /**
     * adds the ability to select the next/previous track
     * @param controller  the controller for callback
     */
    public void setNextPreviousController(Consumer<String> controller) {
        if (controller == null)
            return;
        nextPrevious = controller;
        capabilities.setNextPrevious(true);
    }
```

Throws the exception to be exact

**Comment by jundl77** [comment]
So with updating Izou, the error has changed to this

``` java
Connected to the target VM, address: '127.0.0.1:53609', transport: 'socket'
2015-06-19 13:33:18,110 DEBUG [main] org.intellimate.izou.main.Main (Main.java:92) - Starting Izou
2015-06-19 13:33:18,113 DEBUG [main] org.intellimate.izou.main.Main (Main.java:93) - Initializing...
2015-06-19 13:33:18,310 DEBUG [main] org.intellimate.izou.main.Main (Main.java:115) - Done initializing.
2015-06-19 13:33:18,311 DEBUG [main] org.intellimate.izou.main.Main (Main.java:116) - Adding addons..
2015-06-19 13:33:19,230 DEBUG [main] org.intellimate.izou.main.Main (Main.java:130) - retrieving addons & registering them
2015-06-19 13:33:19,234 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:97) - searching for addons in: /Users/julianbrendl/Google Drive/Programming/Java/Izou/lib
2015-06-19 13:33:19,254 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:100) - loading plugins
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%2520Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced'
[WeavingURLClassLoaderHelper] debug weaving 'javax.sound.sampled.AudioSystem'
[WeavingURLClassLoaderHelper] weaveinfo Join point 'method-execution(javax.sound.sampled.Line javax.sound.sampled.AudioSystem.getLine(javax.sound.sampled.Line$Info))' in Type 'javax.sound.sampled.AudioSystem' (AudioSystem.java:410) advised by around advice from 'org.intellimate.izou.system.sound.replaced.MixerAspect' (MixerAspect.java)
[WeavingURLClassLoaderHelper] debug generating class 'javax.sound.sampled.AudioSystem$AjcClosure1'
[WeavingURLClassLoaderHelper] debug weaving 'org.intellimate.izou.system.sound.replaced.MixerAspect'
[WeavingURLClassLoaderHelper] info AspectJ Weaver Version 1.8.5 built on Thursday Jan 29, 2015 at 01:03:58 GMT
[WeavingURLClassLoaderHelper] info register classloader ro.fortsoft.pf4j.IzouPluginClassLoader$WeavingURLClassLoaderHelper
[WeavingURLClassLoaderHelper] info using configuration /Users/julianbrendl/Google%20Drive/Programming/Java/Izou/target/classes/META-INF/aop.xml
[WeavingURLClassLoaderHelper] info register aspect org.intellimate.izou.system.sound.replaced.MixerAspect
[WeavingURLClassLoaderHelper] warning bad library: '/Users/julianbrendl/Google%2520Drive/Programming/Java/Izou/target/classes/org/intellimate/izou/system/sound/replaced'
[WeavingURLClassLoaderHelper] debug weaving 'javax.sound.sampled.AudioSystem'
[WeavingURLClassLoaderHelper] weaveinfo Join point 'method-execution(javax.sound.sampled.Line javax.sound.sampled.AudioSystem.getLine(javax.sound.sampled.Line$Info))' in Type 'javax.sound.sampled.AudioSystem' (AudioSystem.java:410) advised by around advice from 'org.intellimate.izou.system.sound.replaced.MixerAspect' (MixerAspect.java)
[WeavingURLClassLoaderHelper] debug generating class 'javax.sound.sampled.AudioSystem$AjcClosure1'
[WeavingURLClassLoaderHelper] debug weaving 'org.intellimate.izou.system.sound.replaced.MixerAspect'
2015-06-19 13:33:20,049 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:102) - loaded: [PluginWrapper [descriptor=PluginDescriptor [pluginId=org.intellimate.izou.sdk, pluginClass=org.intellimate.izou.sdk.ZipFileManagerImpl, version=0.7.0, provider=intellimate, dependencies=[PluginDependency [pluginId=org.intellimate.izou, pluginVersion=null]]], pluginPath=/sdk-0.7.0], PluginWrapper [descriptor=PluginDescriptor [pluginId=jundl77.izou.izousound, pluginClass=jundl77.izou.izousound.ZipFileManager, version=1.5.0, provider=Julian Brendl, dependencies=[PluginDependency [pluginId=org.intellimate.izou.sdk, pluginVersion=null]]], pluginPath=/izousound-1.5]]
2015-06-19 13:33:20,049 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:106) - starting plugins
2015-06-19 13:33:20,057 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:112) - retrieving addons from the plugins
2015-06-19 13:33:20,080 DEBUG [main] org.intellimate.izou.addon.AddOnManager (AddOnManager.java:114) - retrieved: [jundl77.izou.izousound.SoundAddOn@420bc288]
2015-06-19 13:33:27,918 DEBUG [Thread-1] org.intellimate.izou.events.EventDistributor (EventDistributor.java:342) - EventFired: Event{type='response', source=Identification{identifiable=jundl77.izou.izousound.outputplugin.AudioFilePlayer@349d952f}, descriptors=[izou.music.events.playerupdate], listResourceContainer=ListResourceProviderImpl{resources=[]}} from jundl77.izou.izousound.outputplugin.AudioFilePlayer
2015-06-19 13:33:39,348 FATAL [Thread-4] org.intellimate.izou.threadpool.ThreadPoolManager (ThreadPoolManager.java:59) - unable to provide callback for: org.intellimate.izou.addon.AddOnManager$$Lambda$51/1986581856@26b3e581
java.util.concurrent.CompletionException: java.lang.NullPointerException
    at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [?:1.8.0_20]
    at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
    at org.intellimate.izou.threadpool.ThreadPoolManager$LoggingThreadFactory$1.run(ThreadPoolManager.java:73) [classes/:?]
Caused by: java.lang.NullPointerException
    at org.intellimate.izou.sdk.frameworks.music.player.template.CommandHandler.setNextPreviousController(CommandHandler.java:85) ~[?:?]
    at jundl77.izou.izousound.outputplugin.AudioFilePlayer.<init>(AudioFilePlayer.java:39) ~[?:?]
    at jundl77.izou.izousound.SoundAddOn.prepare(SoundAddOn.java:26) ~[?:?]
    at org.intellimate.izou.sdk.addon.AddOn.register(AddOn.java:41) ~[?:?]
    at org.intellimate.izou.addon.AddOnManager$$Lambda$51/1986581856.run(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) ~[?:1.8.0_20]
    ... 4 more
```

**Comment by LeanderK** [comment]
i have just released `0.13.3`, it should fix the bug. Can you confirm that? Didn't test it.

**Comment by LeanderK** [comment]
if i manage to release it....

**Comment by jundl77** [comment]
The error is no longer here, (I tested with version 0.13.2, 0.13.3 was never released I think) however I have not tried to play music yet, as I need another addOn to start the request. Ill try it later.

**Comment by LeanderK** [comment]
hmm weird....i hope i didn't introduce a bug in 0.13.3 (no, its not yet released ;) maven central is bitching :P )
